### ISSUE TITLE
End of File

### ISSUE THREAD

**Issue by ddavout** [vegardit/haxe-doctest#1]
despite the workaround in fileInput, MyDocTestRunner.hx is "aborted"
`/home/yop/Bureau/lastone/plaf/haxe/lib/haxe-doctest/1,0,3/src/hx/doctest/internal/SourceFile.hx:41: [INFO] Scanning [src/ActivitiesBuilderCheck.hx]...
/usr/share/haxe/std/neko/_std/sys/io/FileInput.hx:37: characters 4-9 : Eof
/usr/share/haxe/std/haxe/io/Input.hx:176: characters 18-28 : Called from
/usr/share/haxe/std/neko/Lib.hx:60: characters 17-37 : Called from
/usr/share/haxe/std/haxe/io/Input.hx:183: characters 13-50 : Called from
/home/yop/Bureau/lastone/plaf/haxe/lib/haxe-doctest/1,0,3/src/hx/doctest/internal/SourceFile.hx:50: characters 23-43 : Called from
<builtin>:1: character 0 : Called from
/home/yop/Bureau/lastone/plaf/haxe/lib/haxe-doctest/1,0,3/src/hx/doctest/internal/SourceFile.hx:25: lines 25-87 : Called from
/home/yop/Bureau/lastone/plaf/haxe/lib/haxe-doctest/1,0,3/src/hx/doctest/DocTestGenerator.hx:68: characters 22-68 : Called from
/home/yop/Bureau/lastone/plaf/haxe/lib/haxe-doctest/1,0,3/src/hx/doctest/internal/DocTestUtils.hx:112: characters 20-32 : Called from
/home/yop/Bureau/lastone/plaf/haxe/lib/haxe-doctest/1,0,3/src/hx/doctest/DocTestGenerator.hx:67: lines 67-209 : Called from
MyDocTestRunner.hx:1: characters 2-7 : Called from
Aborted
`

haxe version : 3.2.0

**Comment by sebthom** [comment]
Fixed in the new release. Thanks for reporting!
