### ISSUE TITLE
Broken for haxe 4.2 ( I know it's not yet released ).

### ISSUE THREAD

**Issue by nanjizal** [vegardit/haxe-doctest#11]
Noticed both with your libraries test of itself with tink setup and with one of my using utest that haxe-doctest is failing on haxe4.2 ( I downloaded early version of haxe4.2 for the module-statics ). (Normal dox is working as set that up without any issue).
For instance for this lib which only has two tests.
https://github.com/nanjizal/dsHelper
I get the following message after scanning..
```
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/DocTestGenerator.hx:386: [INFO] Generated 2 test assertions.
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:40: characters 31-40 : Unknown identifier : assertion
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:40: characters 31-40 : For optional function argument 'msg'
src/dsHelper/TestdsHelper.hx:15: lines 15-25 : Defined in this class
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:32: characters 31-40 : Unknown identifier : assertion
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:32: characters 31-40 : For optional function argument 'msg'
src/dsHelper/TestdsHelper.hx:15: lines 15-25 : Defined in this class
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:40: characters 31-40 : Unknown identifier : assertion
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:40: characters 31-40 : For optional function argument 'msg'
src/dsHelper/TestdsHelper.hx:15: lines 15-25 : Defined in this class
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:32: characters 31-40 : Unknown identifier : assertion
/usr/local/lib/haxeLibrary/haxe-doctest/git/src/hx/doctest/internal/adapters/UTestDocTestAdapter.hx:32: characters 31-40 : For optional function argument 'msg'
src/dsHelper/TestdsHelper.hx:15: lines 15-25 : Defined in this class
```

**Comment by nanjizal** [comment]
The tests are here, they are actually pretty much just copy from similar project so they should not be a problem.
https://github.com/nanjizal/dsHelper/blob/master/src/dsHelper/flatInterleave/core/Flat32.hx#L9

**Comment by sebthom** [comment]
I published a new release. should be fixed now. thanks for reporting!

**Comment by nanjizal** [comment]
Could you clarify, do I need to make a change?
It seems to error on the first line of this generic code.
_characters 1-8 : Uncaught exception src: No such file or directory_
``` haxe
@:build(hx.doctest.DocTestGenerator.generateDocTests())
@:build(utest.utils.TestBuilder.build())
class TestTrilateral3 extends utest.Test {
    public static function main() {
        var runner = new Runner();
        runner.addCase( new TestTrilateral3() );
        Report.create(runner);
        runner.run();
    }
    function new() {
        super();
    }
}
```

**Comment by sebthom** [comment]
You are not required to change anything. This error says, that the `src` folder holding your source files does not exist. if you are using another name you need to specify that one in the generator, e.g. `@:build(hx.doctest.DocTestGenerator.generateDocTests({srcFolder:"myfolder"}))`

**Comment by nanjizal** [comment]
oh sorry my bad, setup a few repos and I did not put that one in an src, when it had stopped working it was bit harder to set them up right.  Prob should probably adjust that, many thanks for swift fix.
