### ISSUE TITLE
Testing abstracts?

### ISSUE THREAD

**Issue by cambiata** [vegardit/haxe-doctest#2]
Thanx, I like this approach very much!

Is it, or would it be, possible to test abstracts this way aswell as classes?

/ Jonas

**Comment by sebthom** [comment]
Hi Jonas,

I am also using it for abstracts, e.g. https://github.com/vegardit/haxe-concurrent/blob/master/src/hx/concurrent/atomic/AtomicBool.hx

Regards,
Seb

**Comment by cambiata** [comment]
Ah, cool! 
So the DocTestRunner macromagically includes all files in the -cp path(s)?

**Comment by sebthom** [comment]
By default the [DocTestGenerator](https://github.com/vegardit/haxe-doctest/blob/master/src/hx/doctest/DocTestGenerator.hx) scans the directory `src` of your current project. 
You can customize the folder name, e.g. `@:build(hx.doctest.DocTestGenerator.generateDocTests("myfolder/mysources"))`

See: https://github.com/vegardit/haxe-doctest/blob/master/src/hx/doctest/DocTestGenerator.hx#L57
