### ISSUE TITLE
Include JSDocs comment header style?

### ISSUE THREAD

**Issue by cambiata** [vegardit/haxe-doctest#3]
Haxe-doctest only seems to work with test statements where the header is star + **one space** + three greater than-angles. The JSDocs comment header standard seems to be star + **two spaces**.

Would be a good thing to allow any number of spaces and/or tabs, I guess.

**Comment by sebthom** [comment]
You can customize the identifier, e.g.
`@:build(hx.doctest.DocTestGenerator.generateDocTests("src", ".+\\.hx$", "*  >>>"))`

**Comment by cambiata** [comment]
Ah, thanks!
