### ISSUE TITLE
haxe.unit has moved to haxelib utest

### ISSUE THREAD

**Issue by nanjizal** [vegardit/haxe-doctest#4]
**haxe.unit** seems to have moved to **haxelib utest** :(
https://github.com/haxe-utest/utest

I am currently using haxe 4, preview5, I don't create macros often so I was not sure how to adjust the Adaptor for the new structure.

Your readme will likely also need updating

*haxelibs required*
```
-lib utest
-lib haxe-doctest
```

``` haxe
package;
import utest.Runner;
import utest.Test;
@:build(hx.doctest.DocTestGenerator.generateDocTests())
class MyTests extends utest.Test {
    public static function main() {
        var runner = new Runner();
        runner.addCase( new MyTests() );
        runner.run();
    }
    function new() {
        super();
    }
}
```

**Comment by nanjizal** [comment]
By the way very exciting project did not want my issues to come accross just negative they were just the problems I came across when trying to use.  If you do get time to update it for utest I would be keen to explore it's use, but not keen to install older haxe for testing.

**Comment by sebthom** [comment]
Hi,
utest and haxe.unit are not the same. In Haxe 4 the `haxe.unit` package has been moved from standard lib into a separate library hx3compat, so you would need to run haxe with `-lib hx3compat`.

**Comment by nanjizal** [comment]
I only found utest by looking through the Haxe compiler source code, it seems like it's one of Franco's libraries no maintained by one of the current maintainers.
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/compile-each.hxml#L9
https://github.com/HaxeFoundation/haxe/commit/02279f7506bbd6b1395e3a8f65d08bcded5bb1a0

From my understanding hx3compat is only to help with people switching to Haxe4 and not the prefered option when using Haxe4, I don't think it is wise to rely on a shim and certainly not suitable for people creating new tests.

Would it be wise to reopen this, like I said I am not a macro person otherwise I would try to fix.
